server:
  port: 8888
  servlet:
    contextPath: /
spring:
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss # 对返回的时间格式化
    timeZone: GMT+8 # 时区设置
    defaultPropertyInclusion: non_empty
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/photo?useunicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    url: jdbc:mysql://www.guanweiming.com:3306/photo?useunicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: photo
    password: photo
#    username: root
#    password: root
  cache:
    type: caffeine
    cache-names: api_cache
    caffeine:
      spec: maximumSize=300,expireAfterWrite=2m
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
mybatis:
  mapperLocations: mappers/*.xml
swagger:
  enabled: true
  title: 水印照片
  description: 接口
  basePackage: com.water.photo
  version: 1.0
guanweiming:
  cors:
    enabled: true
logging:
  level:
    com.water.photo: debug